### ISSUE TITLE
Question: Plan to Remove CodeSmith Dependency?

### ISSUE THREAD

**Issue by davidshq** [EasyLOB/EasyLOB-2#1]
Not exactly an issue, more of a question:
Do you have any plans to remove CodeSmith dependency?
I'm interested in using EasyLOB but do not have a license for CodeSmith.
Thanks!

**Comment by EasyLOB** [comment]
No.
Code Generation is a key concept for a Framework like EasyLOB and I have used other Code Generation Tools in the past, even Microsoft T4.
But CodeSmith is much more powerfull and fast.
Nowadays it is one of the tools I use most during development.
I understand it's not free but $299 is a fair price for what you get using it.
