### ISSUE TITLE
Multi tenancy

### ISSUE THREAD

**Issue by ktngoykalolo** [EasyLOB/EasyLOB-2#2]
Hello, 
I would like to have more details on the multi tenancy feature: 
-it is possible to use it with a single database? 
- is it optional?

**Comment by EasyLOB** [comment]
Hi,
There are mamy ways to implement Multi-Tenancy ( as you probably already know ).
In the following link ( by ASP.NET Zero, another LOB ASP.NET Framework ) you find all of them:

[Multi Tenancy](https://aspnetboilerplate.com/Pages/Documents/Multi-Tenancy)

Considering the kind of applications I develop my choice was for a Single Deployment ( Code ) and Multiple ( Project ) Databases.
If you  take a look at the Web.config file there are 4 Databases:

**"Project" :: NOT Shared
"AuditTrail" :: NOT Shared, and usually the "Project" Database
"Activity" for Authorization :: may be ( and usually is ) Shared
"Authentication" for Authetication :: may be ( and usually is ) Shared**

To create a **Multi-Tenant** with **Single Database** I would have to:

1. Include a **TenantId** in all Tables
1. Define if the Table would be Shared by all Tenants ( very usefull for a Company with Branches ) or NOT Shared
1. Implement Tenant filtering would be easy inside the Repositories, based on **TenantId**
1. Create a **Tenant** Table
1. Create dropdown in the Login View, so the user could choose in which Tenant he would like to work

As you see the changes are not big but currently I do not have any plans to change it.

Thanks
